# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
locale: fr-FR
title: Olivier Marie-Joseph
name: Olivier Marie-Joseph
tagline:          'A Jekyll theme'
description:      'Blogueur et développeur originaire de la Guadeloupe et breton par adoption.'
url:              http://www.oliviermariejoseph.fr/
baseurl:          /

author:
  name:           'Olivier Marie-Joseph'
  email:          'contact@oliviermariejoseph.fr'
  
social:
  github: olivier-mj
  linkedin: oliviermariejoseph 
  skype: olivier-mj


gems:
- jekyll-feed
- jekyll-timeago
- jekyll-paginate
- github-pages


destination: public

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/olivier-mj/olivier-mj.github.io
