# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
locale: fr-FR
title: Portfolio d'Olivier Marie-Joseph BTS SIO SLAM
name: Olivier Marie-Joseph
tagline: 'Portfolio'
description: 'Développeur Web front & back-end'
url: 
baseurl: https://olivier-mj.github.io/

author:
  name: 'Olivier Marie-Joseph'
  email: 'contact@oliviermariejoseph.fr'
  
social:
  github: olivier-mj
  twitter: don_padre
  linkedin: oliviermariejoseph 
  skype: olivier-mj

gems:
- jekyll-feed
- jekyll-timeago
- jekyll-paginate
- github-pages


paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/olivier-mj/olivier-mj.github.io
