url: http://192.168.1.82:4000/
baseurl:  # does not include hostname
show_dir_listing: false
modedev: true

google_analytics: UA-XXXXXXXX-X

gem:
  - jekyll-admin
  - jekyll-livereload

# Serving
detach:  false
port:    4000
host:    192.168.1.82
# Livereload config
livereload: true     # You no longer need to include --livereload
reload_port: 35729    # If you don't want to use the default port