url: http://localhost:4000
modedev: true

gem:
  - jekyll-admin
  - jekyll-livereload




livereload: true     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port